### ISSUE TITLE
Command resulted in error.. `Command not found` error with release 5.2.0

### ISSUE THREAD

**Issue by avation-cbuliga** [manuth/MarkdownConverter#203]
The following lines are from Extension Host log:
```
[2022-09-27 10:36:11.626] [exthost] [error] Activating extension manuth.markdown-converter failed due to an error:
[2022-09-27 10:36:11.626] [exthost] [error] TypeError: File URL path must be absolute
	at new NodeError (node:internal/errors:371:5)
	at getPathFromURLWin32 (node:internal/url:1390:11)
	at fileURLToPath (node:internal/url:1420:22)
	at get PackageDirectory [as PackageDirectory] (c:\Users\...\.vscode\extensions\manuth.markdown-converter-5.2.0\lib\646.cjs:1:465)
	at C (c:\Users\...\.vscode\extensions\manuth.markdown-converter-5.2.0\lib\646.cjs:1:960)
	at 646 (c:\Users\...\.vscode\extensions\manuth.markdown-converter-5.2.0\lib\646.cjs:1:1018)
	at Function.o (c:\Users\...\.vscode\extensions\manuth.markdown-converter-5.2.0\lib\index.cjs:1:2221)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
```

and from Window log:
```
[2022-09-27 10:23:22.018] [renderer1] [error] [Extension Host] Could not load markdown it plugin TypeError: File URL path must be absolute
	at new NodeError (node:internal/errors:371:5)
	at getPathFromURLWin32 (node:internal/url:1390:11)
	at fileURLToPath (node:internal/url:1420:22)
	at get PackageDirectory [as PackageDirectory] (c:\Users\...\.vscode\extensions\manuth.markdown-converter-5.2.0\lib\646.cjs:1:465)
	at C (c:\Users\...\.vscode\extensions\manuth.markdown-converter-5.2.0\lib\646.cjs:1:960)
	at 646 (c:\Users\...\.vscode\extensions\manuth.markdown-converter-5.2.0\lib\646.cjs:1:1018)
	at Function.o (c:\Users\...\.vscode\extensions\manuth.markdown-converter-5.2.0\lib\index.cjs:1:2221)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-09-27 10:23:34.327] [renderer1] [error] Activating extension 'manuth.markdown-converter' failed: File URL path must be absolute.: TypeError: File URL path must be absolute
```

**Comment by manuth** [comment]
I'm terribly sorry for the inconvenience, I'm about to fix this error.
Sadly, there does not seem to be a way to unpublish specific versions of the extensions.

**Comment by avation-cbuliga** [comment]
Thank you for responding so promptly. Much appreciated..

**Comment by neurolag** [comment]
> Thank you for responding so promptly. Much appreciated..

Thanks, I'm glad to hear you appreciate it 😄
I managed it to get the extension to work again.

I'm sorry for the inconvenience.
The new version has been built and should be available in a short while.

Thanks for using MarkdownConverter

**Comment by avation-cbuliga** [comment]
Works great. Thank you again
